
# Disabled by default
Layout/LineLength:
  Enabled: true
  MaxLength: 180 # default

Lint/ComparisonToBoolean:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/LargeNumbers:
  Enabled: true
  IntMinDigits: 5 # i.e. integers higher than 9999

Style/PredicateName:
  Enabled: true

### DISABLED ###
Lint/DebugCalls:
  Description: Disallows debug-related calls
  MethodNames:
  - p
  - p!
  - pp
  - pp!
  Excluded:
  - src/tanda_webhook/server.cr
  Enabled: false
  Severity: Warning

Documentation/DocumentationAdmonition:
  Enabled: false
